# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'
        cache: maven

    - name: Install Google Chrome
      run: |
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo dpkg -i google-chrome-stable_current_amd64.deb || sudo apt-get -f install -y
        google-chrome --version

    - name: Set up ChromeDriver
      run: |
        CHROME_VERSION=$(google-chrome --version | grep -oP "\d+\.\d+\.\d+")
        wget https://storage.googleapis.com/chrome-for-testing-public/131.0.6778.204/linux64/chromedriver-linux64.zip
        unzip chromedriver-linux64.zip
        sudo mv chromedriver-linux64/chromedriver /usr/bin/chromedriver
        sudo chmod +x /usr/bin/chromedriver

    - name: Start Xvfb
      run: |
        Xvfb :99 -ac &
        export DISPLAY=:99

    - name: Build and run tests with Maven
      env:
        DISPLAY: ":99"
        _JAVA_OPTIONS: "-Dwebdriver.chrome.driver=/usr/bin/chromedriver"
      run: mvn clean verify -Dtestng.dtd.http=true -Dwebdriver.chrome.args="--headless --no-sandbox --disable-dev-shm-usage"
      
    - name: Run API jar
      run: java -jar ./api-testing/src/test/resources/libs/demo-0.0.1-SNAPSHOT.jar > app.log 2>&1 &
        
    - name: Run Test Automation with Maven
      run: mvn clean verify
